apiVersion: apps/v1
kind: Deployment
metadata:
  name: wikiracer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wikiracer
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: wikiracer
    spec:
      containers:
        - name: wikiracer
          image: wikiracer.azurecr.io/wikiracer:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 250m
              memory: 300M
            limits:
              cpu: 250m
              memory: 300M
---
apiVersion: v1
kind: Service
metadata:
  name: wikiracer-lb
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: wikiracer
---

