# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.7.2
        with:
          # SDK version to use. Examples: 2.2.104, 3.1, 3.1.x
          dotnet-version: '5.0.x'

      - name: Docker Login
        uses: docker/login-action@v1.9.0
        with:
          registry: wikiracer.azurecr.io
          username: wikiracer
          password: ${{ secrets.ACR_KEY }}
          
      - name: Restore app
        run: dotnet restore ${{ github.workspace }}/src/WebServer/WebServer.csproj -s https://api.nuget.org/v3/index.json
      
      - name: Build app
        run: dotnet build ${{ github.workspace }}/src/WebServer/WebServer.csproj -v normal
      
      - name: Publish app
        run: dotnet publish ${{ github.workspace }}/src/WebServer/WebServer.csproj -o ${{ github.workspace }}/infra/out/WebServer
      
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.4.0
        with:
          file: ${{ github.workspace }}/infra/Dockerfile
          build-args: |
            COSMOS_KEY=${{secrets.COSMOS_KEY}}
            STORAGE_KEY=${{secrets.STORAGE_KEY}}
          tags: wikiracer.azurecr.io/wikiracer:latest
          push: true
        

